/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appbookelandia.view;

/**
 *
 * @author J. Mateus
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        clientes1 = new javax.swing.JMenuItem();
        clientes2 = new javax.swing.JMenuItem();
        clientes4 = new javax.swing.JMenuItem();
        clientes5 = new javax.swing.JMenuItem();
        clientes6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        produtos1 = new javax.swing.JMenuItem();
        produtos3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        funcionarios = new javax.swing.JMenuItem();
        funcionarios1 = new javax.swing.JMenuItem();
        pedidos = new javax.swing.JMenu();
        pesquisa = new javax.swing.JMenuItem();
        chamados = new javax.swing.JMenu();
        aberturaChamado = new javax.swing.JMenuItem();
        pesquisaChamado = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        produtos2 = new javax.swing.JMenuItem();
        clientes3 = new javax.swing.JMenuItem();
        funcionarios2 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booklandia");
        setResizable(false);

        label1.setText("label1");
        label1.setVisible(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbookelandia/images/abc-block.png"))); // NOI18N

        jMenuBar2.setBackground(new java.awt.Color(255, 51, 102));

        jMenu5.setText("Clientes");

        clientes1.setText("Cadastrar");
        clientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientes1ActionPerformed(evt);
            }
        });
        jMenu5.add(clientes1);

        clientes2.setText("Consultar");
        clientes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientes2ActionPerformed(evt);
            }
        });
        jMenu5.add(clientes2);

        clientes4.setText("Atualizar");
        clientes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientes4ActionPerformed(evt);
            }
        });
        jMenu5.add(clientes4);

        clientes5.setText("Deletar");
        clientes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientes5ActionPerformed(evt);
            }
        });
        jMenu5.add(clientes5);

        clientes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientes6ActionPerformed(evt);
            }
        });
        jMenu5.add(clientes6);

        jMenuBar2.add(jMenu5);

        jMenu4.setText("Produtos");

        produtos1.setText("Cadastrar");
        produtos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtos1ActionPerformed(evt);
            }
        });
        jMenu4.add(produtos1);

        produtos3.setText("Consultar");
        produtos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtos3ActionPerformed(evt);
            }
        });
        jMenu4.add(produtos3);

        jMenuBar2.add(jMenu4);

        jMenu3.setText("Funcionários");

        funcionarios.setText("Cadastrar");
        funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariosActionPerformed(evt);
            }
        });
        jMenu3.add(funcionarios);

        funcionarios1.setText("Consultar");
        funcionarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarios1ActionPerformed(evt);
            }
        });
        jMenu3.add(funcionarios1);

        jMenuBar2.add(jMenu3);

        pedidos.setText("Pedidos");

        pesquisa.setText("Pesquisa");
        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });
        pedidos.add(pesquisa);

        jMenuBar2.add(pedidos);

        chamados.setText("Chamados");

        aberturaChamado.setText("Abertura");
        aberturaChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aberturaChamadoActionPerformed(evt);
            }
        });
        chamados.add(aberturaChamado);

        pesquisaChamado.setText("Pesquisa");
        pesquisaChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaChamadoActionPerformed(evt);
            }
        });
        chamados.add(pesquisaChamado);

        jMenuBar2.add(chamados);

        jMenu6.setText("Cadastrar / Consultar");

        produtos2.setText("Produtos");
        produtos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtos2ActionPerformed(evt);
            }
        });
        jMenu6.add(produtos2);

        clientes3.setText("Clientes");
        clientes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientes3ActionPerformed(evt);
            }
        });
        jMenu6.add(clientes3);

        funcionarios2.setText("Funcionarios");
        funcionarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarios2ActionPerformed(evt);
            }
        });
        jMenu6.add(funcionarios2);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(557, 557, 557)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariosActionPerformed
        // TODO add your handling code here:
        FrmCadFuncionarios funcionario = new FrmCadFuncionarios();
        funcionario.setVisible(true);
    }//GEN-LAST:event_funcionariosActionPerformed

    private void aberturaChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aberturaChamadoActionPerformed
        // TODO add your handling code here:
        FrmCadChamadosAbertura chamado = new FrmCadChamadosAbertura();
        chamado.setVisible(true);
    }//GEN-LAST:event_aberturaChamadoActionPerformed

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed
        // TODO add your handling code here:
        FrmConsultaDePedidos pedido = new FrmConsultaDePedidos();
        pedido.setVisible(true);
    }//GEN-LAST:event_pesquisaActionPerformed

    private void pesquisaChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaChamadoActionPerformed
        // TODO add your handling code here:
        FrmCadChamadosConsulta chamados = new FrmCadChamadosConsulta();
        chamados.setVisible(true);
    }//GEN-LAST:event_pesquisaChamadoActionPerformed

    private void produtos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtos1ActionPerformed
        // TODO add your handling code here:
        FrmCadProdutos produto = new FrmCadProdutos();
        produto.setVisible(true);
    }//GEN-LAST:event_produtos1ActionPerformed

    private void clientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientes1ActionPerformed
        // TODO add your handling code here:
        FrmCadClientes cliente = new FrmCadClientes();
        cliente.setVisible(true);       
    }//GEN-LAST:event_clientes1ActionPerformed

    private void clientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientes2ActionPerformed
        // TODO add your handling code here:
        FrmCadClientes cliente = new FrmCadClientes();
        cliente.setVisible(true); 
    }//GEN-LAST:event_clientes2ActionPerformed

    private void produtos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtos2ActionPerformed

    private void clientes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientes3ActionPerformed

    private void funcionarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcionarios2ActionPerformed

    private void produtos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtos3ActionPerformed
        // TODO add your handling code here:
        FrmCadProdutos produto = new FrmCadProdutos();
        produto.setVisible(true);
    }//GEN-LAST:event_produtos3ActionPerformed

    private void funcionarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarios1ActionPerformed
        // TODO add your handling code here:
       FrmCadFuncionarios funcionario = new FrmCadFuncionarios();
        funcionario.setVisible(true);
    }//GEN-LAST:event_funcionarios1ActionPerformed

    private void clientes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientes4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientes4ActionPerformed

    private void clientes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientes5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientes5ActionPerformed

    private void clientes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientes6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientes6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aberturaChamado;
    private javax.swing.JMenu chamados;
    private javax.swing.JMenuItem clientes1;
    private javax.swing.JMenuItem clientes2;
    private javax.swing.JMenuItem clientes3;
    private javax.swing.JMenuItem clientes4;
    private javax.swing.JMenuItem clientes5;
    private javax.swing.JMenuItem clientes6;
    private javax.swing.JMenuItem funcionarios;
    private javax.swing.JMenuItem funcionarios1;
    private javax.swing.JMenuItem funcionarios2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private java.awt.Label label1;
    private javax.swing.JMenu pedidos;
    private javax.swing.JMenuItem pesquisa;
    private javax.swing.JMenuItem pesquisaChamado;
    private javax.swing.JMenuItem produtos1;
    private javax.swing.JMenuItem produtos2;
    private javax.swing.JMenuItem produtos3;
    // End of variables declaration//GEN-END:variables
}
